# Use an official Python runtime as a parent image
FROM bioperl/bioperl

# Set the working directory to /app
WORKDIR /home/rocker

# Copy the current directory contents into the container at /app
COPY . /home/rocker

### Install any needed packages and stuff
#RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
#USER docker

#RUN adduser --disabled-password --gecos '' docker
#RUN adduser docker sudo
#RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

#USER docker

# Ruby
#RUN apt-get update
RUN sudo apt-get update
RUN sudo apt-get --assume-yes install git
RUN cd
RUN git clone https://github.com/rbenv/rbenv.git /home/.rbenv
RUN echo 'export PATH="/home/.rbenv/bin:$PATH"' >> /home/.bashrc
RUN echo 'eval "$(rbenv init -)"' >> /home/.bashrc
#RUN exec $SHELL
RUN source /home/.bashrc

RUN git clone https://github.com/rbenv/ruby-build.git /home/.rbenv/plugins/ruby-build
RUN echo 'export PATH="/home/.rbenv/plugins/ruby-build/bin:$PATH"' >> /home/.bashrc
#RUN exec $SHELL
RUN source /home/.bashrc

RUN rbenv install 2.3.1
RUN rbenv global 2.3.1


# Make port 80 available to the world outside this container
#EXPOSE 80

# Define environment variable
#ENV NAME World

# Run app.py when the container launches
CMD ["echo", "WE RKKIO'"]
